/**
 * Build-time data layer. Content is files in this repo — exported from the
 * Payload CMS on 2026-09-18 and edited here since:
 *
 *   src/content/pages/<slug>.json          page docs (title, slug, layout[])
 *   src/content/posts/<slug>.md            blog posts: front-matter + HTML body (src/content.config.ts)
 *   src/content/globals/{navigation,footer,seo-settings}.json
 *   public/media/*                         every referenced media file (+ size variants)
 *
 * Types are the CMS doc shapes, unchanged, so every component keeps working.
 * Production (Netlify CONTEXT=production) hides posts with draft: true or a
 * future pubDate; branch deploys show them.
 */

import { getCollection } from 'astro:content'

export const TENANT = 'pathway-academy'

export interface MediaSize {
  url?: string | null
  width?: number | null
  height?: number | null
}

export interface Media {
  id: string | number
  url?: string | null
  alt?: string | null
  width?: number | null
  height?: number | null
  /** Responsive variants pre-generated by the CMS at upload (thumb/card/full). */
  sizes?: Record<string, MediaSize | undefined> | null
}

export interface Block {
  blockType: string
  [key: string]: unknown
}

export interface Page {
  id: string | number
  title: string
  slug: string
  layout?: Block[] | null
}

export interface Post {
  id: string | number
  title: string
  slug: string
  publishedAt?: string | null
  excerpt?: string | null
  coverImage?: Media | null
  contentHtml?: string | null
}

export interface NavItem {
  label: string
  href: string
  children?: NavItem[] | null
}

export interface Footer {
  columns?: { heading?: string | null; links?: { label: string; href: string }[] | null }[] | null
  social?: { platform: string; href: string }[] | null
  contact?: { phone?: string | null; email?: string | null; address?: string | null } | null
  copyright?: string | null
}

export interface SeoSettings {
  titleTemplate?: string | null
  defaultTitle?: string | null
  defaultDescription?: string | null
}

/* ---- Reading ---- */

const files = import.meta.glob<{ default: unknown }>('/src/content/**/*.json', { eager: true })

function docs<T>(collection: string): T[] {
  const prefix = `/src/content/${collection}/`
  return Object.entries(files)
    .filter(([path]) => path.startsWith(prefix))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, mod]) => mod.default as T)
}

function global<T>(name: string): T | null {
  return (files[`/src/content/globals/${name}.json`]?.default as T) ?? null
}

const isProduction = process.env.CONTEXT === 'production'

export async function getPages(): Promise<Page[]> {
  const pages = docs<Page>('pages')
  if (pages.length === 0) throw new Error('src/content/pages/ is empty — refusing to build an empty site.')
  return pages
}

/** Posts, newest first. Production hides drafts and future pubDates. */
export async function getPosts(): Promise<Post[]> {
  const entries = await getCollection('posts')
  const now = Date.now()
  return entries
    .filter((e: any) => !isProduction || (!e.data.draft && e.data.pubDate.getTime() <= now))
    .sort((a: any, b: any) => b.data.pubDate.getTime() - a.data.pubDate.getTime())
    .map((e: any): Post => ({
      id: e.data.cmsId ?? e.id,
      title: e.data.title,
      slug: e.id,
      publishedAt: e.data.pubDate.toISOString(),
      excerpt: e.data.excerpt ?? null,
      coverImage: e.data.coverImage ?? null,
      contentHtml: e.body ?? '',
    }))
}

export async function getNavigation(): Promise<NavItem[]> {
  return global<{ items?: NavItem[] }>('navigation')?.items ?? []
}

export async function getFooter(): Promise<Footer | null> {
  return global<Footer>('footer')
}

export async function getSeoSettings(): Promise<SeoSettings | null> {
  return global<SeoSettings>('seo-settings')
}

/** Media urls are site-relative (/media/<file>) — served from public/media. */
function absoluteUrl(url: string): string {
  return url
}

/** Absolute URL for a media document (local-storage URLs are CMS-relative). */
export function mediaUrl(media: Media | null | undefined): string | null {
  return media?.url ? absoluteUrl(media.url) : null
}

/**
 * srcset built from the CMS's pre-generated upload sizes, smallest first.
 * Null when the doc has none (SVGs, small originals, pre-imageSizes uploads) —
 * callers then fall back to build-time optimization.
 */
export function mediaSrcset(media: Media | null | undefined): string | null {
  const variants = Object.values(media?.sizes ?? {})
    .filter((s): s is MediaSize & { url: string; width: number } => Boolean(s?.url && s?.width))
    .sort((a, b) => a.width - b.width)
    .map((s) => `${absoluteUrl(s.url)} ${s.width}w`)
  return variants.length > 0 ? variants.join(', ') : null
}

export function pageTitle(title: string | undefined, seo: SeoSettings | null): string {
  if (!title) return seo?.defaultTitle ?? 'Pathway Academy'
  const template = seo?.titleTemplate
  return template?.includes('%s') ? template.replace('%s', title) : title
}
