#!/usr/bin/env node
// npm run context — regenerates _context/structure.md. Runs on every commit via
// .githooks/pre-commit. This file is the "what exists" answer for
// pipelines/site-update 02_interpret: discovery is a file, not a query.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { loadBlocks, loadPages, loadCollections, listFiles, readJson, P, ROOT } from './lib.mjs';
import { existsSync } from 'node:fs';

const blocks = loadBlocks();
const pages = loadPages();
const collections = loadCollections();
const out = [];
const h = (s) => out.push('', s, '');
const fieldsOf = (schema) => Object.entries(schema.properties || {}).filter(([k]) => k !== 'block').map(([k, v]) => {
  const t = v.$ref ? v.$ref.split('/').pop() : v.enum ? v.enum.join('|') : v.type === 'array' ? `array<${v.items?.type || v.items?.$ref?.split('/').pop() || '?'}>` : v.type;
  return `${k}${(schema.required || []).includes(k) ? '' : '?'}: ${t}${v.maxLength ? ` ≤${v.maxLength}` : ''}${v.default != null ? ` (default ${JSON.stringify(v.default)})` : ''}`;
});

out.push('# Site structure', '', `_Generated by \`npm run context\` on ${new Date().toISOString().slice(0, 10)}. Do not edit — change the content, then regenerate._`);

h('## Routes');
out.push('| Route | Content file | Published | Blocks (in order) |', '| --- | --- | --- | --- |');
for (const { route, file, page, blocks } of pages) {
  const list = blocks.map((b, i) => `${i + 1}. ${b.name}${b.variant ? ` (${b.variant})` : ''}${b.label ? ` — "${b.label}"` : ''}`).join('<br>');
  out.push(`| \`${route}\` | \`${file}\` | ${page.published === false ? 'no' : 'yes'} | ${list} |`);
}
for (const c of collections) {
  // A collection is a route only if the site has pages for it; otherwise it's data rendered inside blocks.
  const routeName = c.name === 'posts' ? 'blog' : c.name;
  if (!existsSync(join(ROOT, 'src/pages', routeName))) { out.push(`| — | \`${c.folder}/\` | — | data collection (${c.entries.length} entries), rendered inside blocks — no route of its own |`); continue; }
  out.push(`| \`/${routeName}/\` | \`${c.folder}/\` (collection index) | — | list of ${c.name} |`);
  out.push(`| \`/${routeName}/<id>/\` | \`${c.folder}/<id>.${c.pattern.includes('json') ? 'json' : 'md'}\` | per entry | entry |`);
}

h('## Page blocks — every field, as set');
for (const { route, file, page, blocks, shape } of pages) {
  out.push(`### \`${route}\` — \`${file}\``, '');
  const desc = page.description ?? page.seo?.description;
  out.push(`- title: "${page.title}"${desc ? `\n- description: "${desc}"` : ''}${shape === 'cms-export' ? '\n- shape: Payload doc (`layout[]` with `blockType`)' : ''}`);
  const key = shape === 'cms-export' ? 'layout' : 'blocks';
  blocks.forEach((b, i) => {
    out.push('', `**${key}[${i}] ${b.name}**${b.variant ? ` variant=${b.variant}` : ''}`, '');
    for (const [k, v] of Object.entries(b.fields)) if (k !== 'id') out.push(`- \`${k}\`: ${JSON.stringify(v).length > 120 ? JSON.stringify(v).slice(0, 117) + '…' : JSON.stringify(v)}`);
  });
  out.push('');
}

h('## Global content — `src/content/globals/`');
for (const f of listFiles(P.globals, '.json')) {
  const g = readJson(join(P.globals, f));
  out.push(`- \`${f}\` — keys: ${Object.keys(g).join(', ')}${f === 'announcements.json' ? ` (${g.items.length} items; schema = Announcement block)` : ''}`);
}

h(Object.keys(blocks).length ? '## Block library — `src/blocks/`' : '## Block library');
if (!Object.keys(blocks).length) out.push('No local block schemas: blocks are rendered by the site\'s own components (or `@gigawatt/blocks`). Block types in use: ' + [...new Set(pages.flatMap((p) => p.blocks.map((b) => b.name)))].sort().join(', ') + '.');
for (const [name, { schema }] of Object.entries(blocks)) {
  out.push(`### ${name} v${schema['x-version']}`, '', schema['x-description'] || '', '', ...fieldsOf(schema).map((f) => `- ${f}`), '');
}

h('## Collections — `src/content.config.ts`');
for (const c of collections) {
  out.push(`### ${c.name} — \`${c.folder}/${c.pattern}\``, '', ...c.fields.map((f) => (f.def === 'json' ? `- ${f.key}` : `- ${f.key}: \`${f.def}\``)), '', `Entries (${c.entries.length}):`, '');
  for (const e of c.entries) out.push(`- \`${e.file}\` — "${e.data.title}" pubDate=${e.data.pubDate}${e.data.draft === true ? ' **draft**' : ''}`);
  out.push('');
}

h('## Media');
out.push(`- \`src/assets/media/\` — ${listFiles(P.media).length} files: ${listFiles(P.media).join(', ') || '(none)'}`);
out.push(`- \`src/assets/files/\` — ${listFiles(P.files).length} files: ${listFiles(P.files).join(', ') || '(none)'}`);
const pub = join(ROOT, 'public/media');
if (existsSync(pub)) out.push(`- \`public/media/\` — ${listFiles(pub).length} files (CMS export; referenced as /media/<file>)`);

h('## Schema versions');
for (const [name, { schema }] of Object.entries(blocks)) out.push(`- ${name}: ${schema['x-version']}`);
out.push(`- collections config: \`src/content.config.ts\``);

h('## Editing rules that apply here');
out.push('- Only `src/content/**` and `src/assets/**` are content. Everything else is a build change.', '- Announcement is a global: edit `globals/announcements.json`, never add it to a page.', '- Removing = `published: false` on a page or `draft: true` on an entry. Never delete.', '- See `_config/standards/content-editing.md` in the workspace.');

mkdirSync(P.context, { recursive: true });
writeFileSync(join(P.context, 'structure.md'), out.join('\n').replace(/\n{3,}/g, '\n\n') + '\n');
console.log(`✓ _context/structure.md — ${pages.length} pages, ${Object.keys(blocks).length} blocks, ${collections.length} collections`);
